# this file is a helper to run manavino locally
# starts a postgres instance on port 5450 to use as a local db
version: "3.6"
services:
  mysql:
    platform: linux/x86_64
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "sat0shi-store-dev"
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=password --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 5

  mysql_is_ready:
    platform: linux/x86_64
    image: mysql
    depends_on:
      mysql:
        condition: service_healthy
